### ISSUE TITLE
Fast broadcast for ExtendedJumpArray and CoupledArray does not work with AbstractArray

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/JumpProcesses.jl#14]
https://github.com/JuliaDiffEq/DiffEqJump.jl/commit/61973124ea88348bea5b1dbf915fd8413196dbcc

Could not find out how to get the views right to split them from the generated function.

**Comment by isaacsas** [comment]
@ChrisRackauckas can we close this?
