### ISSUE TITLE
Use FunctionWranglers.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/JumpProcesses.jl#172]
https://github.com/tisztamo/FunctionWranglers.jl
https://discourse.julialang.org/t/ann-functionwranglers-jl-fast-inlined-execution-of-arrays-of-functions/48770

>FunctionWrappers improved performance with 20-30%. FunctionWranglers added another 30-40% over it. FunctionWrappers is lower-level API that gives you type-stability for a single call. It does not unroll your loops, so it may be better when the list of functions changes often. And it has a ~15ns overhead on every call, which is smaller than a dynamic dispatch, but still a lot compared to a simple calculation.

**Comment by isaacsas** [comment]
We could perhaps drop the recursive call structure in `Direct` using this.

I guess it wouldn’t be good when there are *many* functions to call, but perhaps we can structure the methods to use this when the number of constant rate jumps is < 200(?) or so, and use function wrappers above that (just using the number from the readme).

**Comment by ChrisRackauckas** [comment]
Yeah it's probably worth investigating whether this matches the recursive call structure in performance, but also that it allows up to 200 effectively. If so, then having this and FunctionWrappers would be a good combo.

**Comment by isaacsas** [comment]
For most other SSAs we use dependency graphs, so only call a few functions (randomly). I guess in that context this won’t help. But we should definitely investigate for `Direct`.

**Comment by isaacsas** [comment]
I'm closing this as it seems the package isn't really maintained anymore.
