### ISSUE TITLE
Plotting is misleading when not saving all jumps

### ISSUE THREAD

**Issue by isaacsas** [SciML/JumpProcesses.jl#206]
If we aren't saving all jumps, it seems like we shouldn't use a piecewise-constant curve. Maybe a straight piecewise linear plot would make more sense?

**Comment by isaacsas** [comment]
@ChrisRackauckas would a reasonable way to handle this be to not set constant interpolation here: https://github.com/SciML/JumpProcesses.jl/blob/4d82cef7b6ce6bc9abbdcf716bd12b9b62c16b15/src/SSA_stepper.jl#L189 when we detect we aren't saving at all times?

**Comment by isaacsas** [comment]
I guess setting linear interpolation or such instead?

**Comment by ChrisRackauckas** [comment]
Yeah we could set that to LinearInterpolation, though it would be a type instability in the output.
