### ISSUE TITLE
Consider a rename

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/JumpProcesses.jl#242]
JumpProcesses.jl, StochasticSimulationAlgorithms.jl, GilespieProcesses.jl, etc.

**Comment by isaacsas** [comment]
JumpProcesses.jl seems good to me. Pretty much sums up the package, allows for non-SSA methods which is a longer-term goal, and maybe makes more sense since this can be used as a component in mixed models.

**Comment by ChrisRackauckas** [comment]
![Screenshot 2022-06-20 111207](https://user-images.githubusercontent.com/1814174/174632477-29544887-7d7e-4760-b8bb-7db5ca8e02b9.png)

**Comment by ChrisRackauckas** [comment]
Okay cool, it really stuck out as the non-informative name of the bunch 😅

**Comment by isaacsas** [comment]
Yeah, I noticed that myself.
