### ISSUE TITLE
Needs type constraint

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/JumpProcesses.jl#269]
https://github.com/SciML/JumpProcesses.jl/blob/7d7905b8733f886a261a823614373fbe69a4ee71/src/SSA_stepper.jl#L105

Otherwise it is the default implementation, which it is not.

**Comment by isaacsas** [comment]
Wow, that is a pretty old piece of code too for that to have not been caught before. Perhaps it is the appropriate default `solve!` /s.
