### ISSUE TITLE
get_concrete_problem does not preserve ExtendedJumpArray when it is initialized as an integer

### ISSUE THREAD

**Issue by gzagatti** [SciML/JumpProcesses.jl#275]
JumpProcess.jl does some tricks to handle `VariableJumps`. However, I might have found a small bug in the current implementation.

Let's say we have the following model taken from the [tutorial](https://docs.sciml.ai/JumpProcesses/stable/tutorials/simple_poisson_process/):

```julia
using JumpProcesses, OrdinaryDiffEq

p = (λ = 2.0, μ = 1.5)

deathrate(u,p,t) = p.μ * u[1]
deathaffect!(integrator) = (integrator.u[1] -= 1; integrator.u[2] += 1)
deathvrj = VariableRateJump(deathrate, deathaffect!)

rate1(u,p,t) = p.λ * (sin(pi*t/2) + 1)
affect1!(integrator) = (integrator.u[1] += 1)
vrj = VariableRateJump(rate1, affect1!)

function f!(du, u, p, t)
    du .= 0
    nothing
end
u₀ = [0., 0.]
oprob = ODEProblem(f!, u₀, tspan, p)
jprob = JumpProblem(oprob, Direct(), vrj, deathvrj)

sol = solve(jprob, Tsit5())
```

This works perfectly. However, if we modify `u0` from a `Float64` to an `Int` array `u0 = [0, 0]`. Then `solve` raises an exception which basically complains that there is no method matching `(::JumpProcess)(::Vector{Float64}, ::Vector{Float64}, ...)` since it is looking for a method matching `(::JumpProcess)(::ExtendedJumpArray, ::ExtendedJumpArray, ...)`. This makes total sense since JumpProcess.jl remakes `oprob` to use an `ExtendedJumpArray`. 

So what's going on? After some digging around the source code, it turns out that the culprit is located in this line of [`DiffEqBase.jl/src/solve.jl`](https://github.com/SciML/DiffEqBase.jl/blob/89e2a5fc77f495a02bf2ebe6530fddea95630eba/src/solve.jl#L1040).

```julia
isadapt && eltype(u0) <: Integer && (u0 = float.(u0))
```

When dealing with jump processes, it is common to be interested in modelling counts so having `u₀` as an array of integers is a reasonable choice.

It's probably the case that you only want to convert the extended part of the array to float. However, I'm not sure if that's possible.

In any case, you should preserve `u0` as an `ExtendedJumpArray` that it works even after conversion.

**Comment by isaacsas** [comment]
@gzagatti seems closed by https://github.com/SciML/JumpProcesses.jl/pull/340.

**Comment by gzagatti** [comment]
Awesome! Thanks @meson800!
