### ISSUE TITLE
possible interpolation bug in hybrid systems

### ISSUE THREAD

**Issue by isaacsas** [SciML/JumpProcesses.jl#361]
@ChrisRackauckas I pinged you on Discourse, but this seems like there is something wrong with interpolation in hybrid jump-ODE systems?

https://discourse.julialang.org/t/missing-precision-in-the-solution-of-combinations-of-ode-and-jump-processes-using-differentialequations-jl-and-jumpprocesses-jl/105370

**Comment by ChrisRackauckas** [comment]
Seems like it was just a continuity choice.
