### ISSUE TITLE
figure out why CI is now taking a ridiculous amount of time

### ISSUE THREAD

**Issue by isaacsas** [SciML/JumpProcesses.jl#410]
CI is suddenly taking a very long amount of time, while not actually reporting that any specific test file is taking a long time (it seems to hang for a very long time on the saveat_regression test, while not actually reporting that it spends much time on this file). Locally on my computer I have no issues -- this only seems to be the Github action that is problematic.

**Comment by isaacsas** [comment]
https://github.com/SciML/JumpProcesses.jl/pull/411 seems to have fixed this issue.

**Comment by ChrisRackauckas** [comment]
Deprecation warnings really slow down code, so fixing them would definitely fix this.
