### ISSUE TITLE
`FunctionMap` not defined

### ISSUE THREAD

**Issue by TorkelE** [SciML/JumpProcesses.jl#423]
Probably working as intended but:
```julia
using JumpProcesses
SSAStepper() # Works
FunctionMap() # Not defined
```

Does JumpPrcoesses export any solvers more than `SSAStepper`, or is this the only one?

**Comment by TorkelE** [comment]
Any reason it is not used as the default choice in that case? If you build a `JumpProblem` on an `ODEProblem` or a `SDEProblem` it doesn't make sense, but I think `DiscreteProblem` is basically the one people use. It should also be easy to detect what problem was provided to `JumpProblem` and use that to determine if a default can (or cannot) be selected.

**Comment by isaacsas** [comment]
I’m going to close this as FunctionMap is not part of JumpProcesses and there is already one or more issues about default solver selection.

**Comment by ChrisRackauckas** [comment]
It's implemented as part of OrdinaryDiffEq using its infrastructure so that callbacks are fully supported. It's pretty tied to its internals.

**Comment by TorkelE** [comment]
Makes sense. I was writing the section on designation of solver for jump simulations, and was trying to figure out if there was an alternative one (to `SSAStepper`) that I could use for the example. I will just import OrdinaryDiffEq and use `FunctionMap`.

**Comment by isaacsas** [comment]
Use SSAStepper for a pure jump simulation. It is much faster and designed for such simulations. There is no reason to use FunctionMap.

**Comment by TorkelE** [comment]
So right now I sue `SSAStepper` for everything. But at the end of the Jump simulation tutorial I wanted to have a bit on how to select jump simulation solver, and wanted an example with another solver one could use in place of `SSAStepper`. That's where `FunctionMap` came into the picture (although the only reason to use it seems to be continuous callbacks, but given that continuous events do not work, I am not sure about the callbacks).

I could also remove the section, and say that while you technically could change the solver, it is related to other functionality, and that they should always use `SSAStepper`.
