### ISSUE TITLE
don't alias user tstops when modifying it in SSAStepper

### ISSUE THREAD

**Issue by isaacsas** [SciML/JumpProcesses.jl#442]
`add_tstops` should copy on write, or we should just copy in `init`. Otherwise this seems like it may lead to bugs when repeatedly calling `solve`.

**Comment by ChrisRackauckas** [comment]
I think we generally need to setup a keyword system on what to alias and what not to alias for all arguments.

**Comment by isaacsas** [comment]
I also set copy on first write as the default behavior when not aliasing.
