### ISSUE TITLE
ODE-jump models with implicit solvers not working

### ISSUE THREAD

**Issue by isaacsas** [SciML/JumpProcesses.jl#459]
Motivated by https://discourse.julialang.org/t/jumpprocesses-jl-solvers/121883 which seems to get an error instead, I am finding
```julia
using JumpProcesses, OrdinaryDiffEq
p = [2.0, 1.0]
u0 = [1.0]
tspan = (0.0, 4.0)

function ode_fxn(du, u, p, t)
    du .= 0
    nothing
end

b_rate(u, p, t) = (u[1] * p[1])
function birth!(integrator)
    integrator.u[1] += 1
    nothing
end
b_jump = VariableRateJump(b_rate, birth!)

d_rate(u, p, t) = (u[1] * p[2])
function death!(integrator)
    integrator.u[1] -= 1
    nothing
end
d_jump = VariableRateJump(d_rate, death!)

ode_prob = ODEProblem(ode_fxn, u0, tspan, p)
sjm_prob = JumpProblem(ode_prob, b_jump, d_jump)
sol = solve(sjm_prob, ImplicitEuler())
```
gives
```
┌ Warning: At t=0.0, dt was forced below floating point epsilon 5.0e-324, and step error estimate = 1.0. Aborting. There is either an error in your model specification or the true solution is unstable (or the true solution can not be represented in the precision of Float64).
└ @ SciMLBase ~/.julia/packages/SciMLBase/fqdZV/src/integrator_interface.jl:623
retcode: Unstable
Interpolation: 3rd order Hermite
t: 1-element Vector{Float64}:
 0.0
u: 1-element Vector{ExtendedJumpArray{Float64, 1, Vector{Float64}, Vector{Float64}}}:
 [1.0]
```
while
```julia
julia> sol = solve(sjm_prob, Rodas5())
retcode: Success
Interpolation: specialized 4rd order "free" stiffness-aware interpolation
t: 724-element Vector{Float64}:
 0.0
 0.004127525454249106
 0.0059311904982310764
 0.0077675951067161225
 0.009603999715201168
 0.011440404323686213
 0.013276808932171258
 0.015113213540656303
 0.016949618149141348
 0.018786022757626395
 0.020622427366111442
 0.02245883197459649
 0.024295236583081536
 0.026131641191566583
 0.02796804580005163
 0.029804450408536676
 0.03164085501702172
 0.03347725962550677
 0.035313664233991814
 0.03715006884247686
 0.03898647345096191
 0.040822878059446954
 0.042659282667932
 0.04449568727641705
 0.046332091884902095
 0.04816849649338714
 0.05000490110187219
 0.051841305710357236
 0.05367771031884228
 0.05551411492732733
 0.057350519535812376
 0.05918692414429742
 0.06102332875278247
 ⋮
 3.535887868639177
 3.550138043902331
 3.5644426672952085
 3.5788019468572734
 3.593216091422883
 3.6076853116218945
 3.622209817895197
 3.6367898203665967
 3.6514255310796524
 3.666117162888113
 3.680864929459014
 3.6956690452757828
 3.7105297256413605
 3.7254471866813312
 3.7404216453470664
 3.7554533194188795
 3.7705424275091937
 3.785689187900973
 3.8008938220407074
 3.816156549882591
 3.831477593390414
 3.8468571765586956
 3.8622955218724875
 3.877792853849562
 3.8933493990617847
 3.9089653825541872
 3.9246410314279094
 3.94037657486182
 3.9561722404903854
 3.9720282580278385
 3.987944858066102
 4.0
u: 724-element Vector{ExtendedJumpArray{Float64, 1, Vector{Float64}, Vector{Float64}}}:
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 ⋮
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
```
But this works fine with Tsit5().

**Comment by isaacsas** [comment]
For reference, the mean solution here is `exp(t)` on [0,4] which Tsit5() captures.

**Comment by isaacsas** [comment]
Very strange. This is a really busy week for me, so I might not get to help investigate this till Friday or the weekend. If you wanted to play around you could try changing the linear solver to a matrix-free Krylov method and see if that helps: https://docs.sciml.ai/DiffEqDocs/stable/tutorials/advanced_ode_example/#Using-Jacobian-Free-Newton-Krylov

**Comment by ChrisRackauckas** [comment]
For both of you, are you on a Mac or Intel machine? 

The following should work for you for now:

```julia
sol = solve(jump_prob, Rodas4(linsolve = LUFactorization()))
sol = solve(jump_prob, Rodas4(linsolve = RFLUFactorization()))
```

Since I just moved I don't have all of my machines around, but I can see on my Mac that the issue is that we too readily default to AppleAccelerate overloads on a non-contiguous b vector.

**Comment by ChrisRackauckas** [comment]
The other case that might be problematic which I cannot test right now is MKL, which is why I asked for if anyone has an Intel. Even if it's just an X86 though you can at least try and check:

```julia
sol = solve(jump_prob, Rodas4(linsolve = MKLLUFactorization()))
```

My guess is that it will likely have the same behavior as the Apple one.

I'm trying to think though if there's a better solution than just not defaulting to the tuned BLAS in these cases. That might be the easiest robust solution though.

**Comment by isaacsas** [comment]
I'm on a mac.

**Comment by isaacsas** [comment]
@ChrisRackauckas do you have any idea about the issue with the simple birth-death example I posted? Is it degenerate for some reason due to `du .= 0`? (I don't see why that should cause problems though -- the solutions show lots of time points but no jumps occurring.)

**Comment by isaacsas** [comment]
(We actually use that one in the tests, so once it is working I will update the tests to check correctness against one or more implicit methods too.)

**Comment by hhindley** [comment]
I am also on a mac, using those above solvers does get rid of the error but I still hit MaxIters when run for a longer timespan.

**Comment by ChrisRackauckas** [comment]
It's degenerate because the starting rate value ends up negative:

```julia
julia> sol[1]
3-element ExtendedJumpArray{Float64, 1, Vector{Float64}, Vector{Float64}}:
  1.0
 -1.2064836293851149
 -0.8345225253385252
```

so it never rootfinds. So @isaacsas your case is different from @hhindley 's. Why that starts negative is a bit of a mystery though

**Comment by isaacsas** [comment]
The method relies on them being negative initially though? (i.e. we use the initial values `-randexp()`, and then the idea is it integrates the intensity until the time where the integral plus these values are zero.)

**Comment by ChrisRackauckas** [comment]
Then the rate should be positive, but we somehow have a negative rate here.

**Comment by isaacsas** [comment]
Could the nonlinear and/or linear solve be introducing small negative values even though `f(du,u,p,t)` just sets `du .= 0`?

**Comment by isaacsas** [comment]
> I am also on a mac, using those above solvers does get rid of the error but I still hit MaxIters when run for a longer timespan.

But is this now consistent for both implicit and explicit solvers? If so, is it due to the frequency of jump firing? You can't "skip over" jumps with an implicit solver, so you'll still need to resolve each one. If you don't need / want to resolve each exact jump you'd need to use a tau-leaping approach instead.

**Comment by ChrisRackauckas** [comment]
This is a bug. I haven't taken the time to figure out why it's going in the wrong direction, but it is.

**Comment by ChrisRackauckas** [comment]
> Could the nonlinear and/or linear solve be introducing small negative values even though f(du,u,p,t) just sets du .= 0? (Perhaps from the coupling to the integrated intensity values, which are not zero.)

Yes that's possible due to LU factorization error growth. https://github.com/SciML/OrdinaryDiffEq.jl/issues/1651 details exactly how that can happen.

**Comment by ChrisRackauckas** [comment]
```julia
using JumpProcesses, OrdinaryDiffEq
p = [2.0, 1.0]
u0 = [1.0]
tspan = (0.0, 4.0)

function ode_fxn(du, u, p, t)
    du .= 0
    nothing
end

b_rate(u, p, t) = (u[1] * p[1])
function birth!(integrator)
    integrator.u[1] += 1
    nothing
end
b_jump = VariableRateJump(b_rate, birth!)

d_rate(u, p, t) = (u[1] * p[2])
function death!(integrator)
    integrator.u[1] -= 1
    nothing
end
d_jump = VariableRateJump(d_rate, death!)

ode_prob = ODEProblem(ode_fxn, u0, tspan, p)
sjm_prob = JumpProblem(ode_prob, b_jump, d_jump)

using LinearSolve
sol = solve(sjm_prob, Rodas5P(linsolve = QRFactorization()))
```

```
retcode: Success
Interpolation: specialized 4rd order "free" stiffness-aware interpolation
t: 827-element Vector{Float64}:
 0.0
 0.033531107529250564
 0.033531107529250564
 ⋮
 3.9993533353919233
 3.9993533353919233
 4.0
u: 827-element Vector{ExtendedJumpArray{Float64, 1, Vector{Float64}, Vector{Float64}}}:
 [1.0]
 [1.0]
 [2.0]
 ⋮
 [115.99999999999999]
 [114.99999999999999]
 [114.99999999999999]
```

Correcting for the numerical error via QRFactorization fixes @isaacsas 's case as expected due to the issue linked above.
